version: '2'
services:
  slim:
    image: comicrelief/php7-slim:latest
    volumes:
      - /Users/chiaraferrazza/Sviluppo/slimCodekata:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: local
      DB_HOST: mysql
      DB_DATABASE: project
      DB_USER: project
      DB_PASSWORD: project

  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project